"""Definitions for TrueNAS sensor entities."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, NamedTuple

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfDataRate,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfFrequency,
    UnitOfInformation,
    UnitOfTemperature,
    UnitOfTime,
)
from homeassistant.helpers.entity import EntityCategory

from .const import (
    ICON_GAUGE,
    LINK_STATE_DOWN,
    SCHEMA_SERVICE_CLOUDSYNC_ABORT,
    SCHEMA_SERVICE_CLOUDSYNC_RUN,
    SCHEMA_SERVICE_DATASET_LOCK,
    SCHEMA_SERVICE_DATASET_SNAPSHOT,
    SCHEMA_SERVICE_DATASET_UNLOCK,
    SCHEMA_SERVICE_REPLICATION_RUN,
    SCHEMA_SERVICE_RSYNC_RUN,
    SCHEMA_SERVICE_SNAPSHOTTASK_RUN,
    SCHEMA_SERVICE_SYSTEM_REBOOT,
    SCHEMA_SERVICE_SYSTEM_SHUTDOWN,
    SERVICE_CLOUDSYNC_ABORT,
    SERVICE_CLOUDSYNC_RUN,
    SERVICE_DATASET_LOCK,
    SERVICE_DATASET_SNAPSHOT,
    SERVICE_DATASET_UNLOCK,
    SERVICE_REPLICATION_RUN,
    SERVICE_RSYNC_RUN,
    SERVICE_SNAPSHOTTASK_RUN,
    SERVICE_SYSTEM_REBOOT,
    SERVICE_SYSTEM_SHUTDOWN,
)

# Icons reused by several entity descriptions.
ICON_MEMORY = "mdi:memory"
ICON_DATABASE_SETTINGS = "mdi:database-settings"

DEVICE_ATTRIBUTES_NETWORK = (
    "description",
    "mtu",
    "link_state",
    "active_media_type",
    "active_media_subtype",
    "link_address",
)

DEVICE_ATTRIBUTES_POOL = (
    "path",
    "status",
    "healthy",
    "is_decrypted",
    "autotrim",
    "scrub_state",
    "scrub_start",
    "scrub_end",
    "scrub_secs_left",
    "usage",
)

DEVICE_ATTRIBUTES_POOL_ERRORS = (
    "read_errors",
    "write_errors",
    "checksum_errors",
)

DEVICE_ATTRIBUTES_DATASET = (
    "type",
    "pool",
    "mountpoint",
    "deduplication",
    "atime",
    "casesensitivity",
    "checksum",
    "exec",
    "sync",
    "compression",
    "compressratio",
    "quota",
    "copies",
    "readonly",
    "recordsize",
    "encryption_algorithm",
    "encryption_key_format",
    "encrypted",
    "locked",
    "used",
    "available",
)

DEVICE_ATTRIBUTES_DISK = (
    "serial",
    "size",
    "hddstandby",
    "hddstandby_force",
    "advpowermgmt",
    "acousticlevel",
    "togglesmart",
    "model",
    "rotationrate",
    "type",
    "name",
    "devname",
    "zfs_guid",
    "identifier",
)

DEVICE_ATTRIBUTES_CPU: tuple[str, ...] = ()

DEVICE_ATTRIBUTES_MEMORY = (
    "memory-free_value",
    "memory-total_value",
)

DEVICE_ATTRIBUTES_CLOUDSYNC = (
    "direction",
    "path",
    "enabled",
    "transfer_mode",
    "snapshot",
    "time_started",
    "time_finished",
    "job_percent",
    "job_description",
)

DEVICE_ATTRIBUTES_REPLICATION = (
    "source_datasets",
    "target_dataset",
    "recursive",
    "enabled",
    "direction",
    "transport",
    "auto",
    "retention_policy",
    "state",
    "time_started",
    "time_finished",
    "job_percent",
    "job_description",
)

DEVICE_ATTRIBUTES_RSYNC = (
    "path",
    "remotehost",
    "remotemodule",
    "direction",
    "mode",
    "enabled",
    "time_started",
    "time_finished",
    "job_percent",
    "job_description",
)

DEVICE_ATTRIBUTES_SNAPSHOTTASK = (
    "recursive",
    "lifetime_value",
    "lifetime_unit",
    "enabled",
    "naming_schema",
    "allow_empty",
    "vmware_sync",
    "state",
    "datetime",
)

DEVICE_ATTRIBUTES_ALERTS = (
    "messages",
    "critical",
    "warning",
    "info",
)

DEVICE_ATTRIBUTES_DIRECTORYSERVICE = (
    "type",
    "status_msg",
    "domain",
    "kerberos_realm",
    "account_cache",
    "dns_updates",
    "site",
)


@dataclass
class TrueNASSensorEntityDescription(SensorEntityDescription):
    """Class describing entities."""

    ha_group: str | None = None
    ha_connection: str | None = None
    ha_connection_value: str | None = None
    data_path: str | None = None
    data_attribute: str | None = None
    data_name: str | None = None
    data_uid: str | None = None
    data_reference: str | None = None
    data_attributes_list: list[str] = field(default_factory=list)
    # Optional (key, value): skip creating an entity for a referenced object
    # whose data[key] == value (e.g. don't create traffic sensors for a
    # network interface whose link is down).
    data_exclude: tuple[str, Any] | None = None
    func: str = "TrueNASSensor"


SENSOR_TYPES: tuple[TrueNASSensorEntityDescription, ...] = (
    TrueNASSensorEntityDescription(
        key="alerts",
        name="Alerts",
        icon="mdi:alert",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="alerts",
        data_attribute="count",
        data_name=None,
        data_uid=None,
        data_reference=None,
        data_attributes_list=DEVICE_ATTRIBUTES_ALERTS,
    ),
    TrueNASSensorEntityDescription(
        key="system_smb_connections",
        name="SMB connections",
        icon="mdi:folder-network",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="smb_connections",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="system_uptime",
        name="Uptime",
        icon="mdi:clock-outline",
        native_unit_of_measurement=None,
        device_class=SensorDeviceClass.UPTIME,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="uptimeEpoch",
        data_name=None,
        data_uid=None,
        data_reference=None,
        func="TrueNASUptimeSensor",
    ),
    TrueNASSensorEntityDescription(
        key="system_cpu_temperature",
        name="Temperature",
        icon="mdi:thermometer",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        suggested_unit_of_measurement=UnitOfTemperature.CELSIUS,
        suggested_display_precision=0,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="cpu_temperature",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="system_load_shortterm",
        name="CPU load shortterm",
        icon=ICON_GAUGE,
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="load_shortterm",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="system_load_midterm",
        name="CPU load midterm",
        icon=ICON_GAUGE,
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="load_midterm",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="system_load_longterm",
        name="CPU load longterm",
        icon=ICON_GAUGE,
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="load_longterm",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="system_cpu_usage",
        name="CPU usage",
        icon="mdi:cpu-64-bit",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="cpu_usage",
        data_name=None,
        data_uid=None,
        data_reference=None,
        data_attributes_list=DEVICE_ATTRIBUTES_CPU,
    ),
    TrueNASSensorEntityDescription(
        key="system_memory_usage",
        name="Memory usage",
        icon=ICON_MEMORY,
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="memory-usage_percent",
        data_name=None,
        data_uid=None,
        data_reference=None,
        data_attributes_list=DEVICE_ATTRIBUTES_MEMORY,
    ),
    TrueNASSensorEntityDescription(
        key="system_cache_size-arc_value",
        name="ARC size",
        icon=ICON_MEMORY,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_unit_of_measurement=UnitOfInformation.GIBIBYTES,
        suggested_display_precision=1,
        device_class=SensorDeviceClass.DATA_SIZE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="cache_size-arc_value",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="system_memory_total",
        name="Memory total",
        icon=ICON_MEMORY,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_unit_of_measurement=UnitOfInformation.GIBIBYTES,
        suggested_display_precision=1,
        device_class=SensorDeviceClass.DATA_SIZE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="memory-total_value",
        data_name=None,
        data_uid=None,
        data_reference=None,
        data_attributes_list=DEVICE_ATTRIBUTES_MEMORY,
    ),
    TrueNASSensorEntityDescription(
        key="system_memory_free",
        name="Memory free",
        icon=ICON_MEMORY,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_unit_of_measurement=UnitOfInformation.GIBIBYTES,
        suggested_display_precision=1,
        device_class=SensorDeviceClass.DATA_SIZE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="system_info",
        data_attribute="memory-free_value",
        data_name=None,
        data_uid=None,
        data_reference=None,
        data_attributes_list=DEVICE_ATTRIBUTES_MEMORY,
    ),
    TrueNASSensorEntityDescription(
        key="dataset",
        name="",
        icon="mdi:database",
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_unit_of_measurement=UnitOfInformation.GIBIBYTES,
        suggested_display_precision=0,
        device_class=SensorDeviceClass.DATA_SIZE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="Datasets",
        data_path="dataset",
        data_attribute="used",
        data_name="name",
        data_uid=None,
        data_reference="id",
        data_attributes_list=DEVICE_ATTRIBUTES_DATASET,
        func="TrueNASDatasetSensor",
    ),
    TrueNASSensorEntityDescription(
        key="disk",
        name="",
        icon="mdi:harddisk",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        suggested_unit_of_measurement=UnitOfTemperature.CELSIUS,
        suggested_display_precision=0,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="Disks",
        data_path="disk",
        data_attribute="temperature",
        data_name="name",
        data_uid=None,
        data_reference="identifier",
        data_attributes_list=DEVICE_ATTRIBUTES_DISK,
    ),
    TrueNASSensorEntityDescription(
        key="pool_free",
        name="free",
        icon=ICON_DATABASE_SETTINGS,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_unit_of_measurement=UnitOfInformation.GIBIBYTES,
        suggested_display_precision=0,
        device_class=SensorDeviceClass.DATA_SIZE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="Pools",
        data_path="pool",
        data_attribute="available",
        data_name="name",
        data_uid=None,
        data_reference="guid",
        data_attributes_list=DEVICE_ATTRIBUTES_POOL,
    ),
    TrueNASSensorEntityDescription(
        key="pool_size",
        name="size",
        icon=ICON_DATABASE_SETTINGS,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_unit_of_measurement=UnitOfInformation.GIBIBYTES,
        suggested_display_precision=0,
        device_class=SensorDeviceClass.DATA_SIZE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="Pools",
        data_path="pool",
        data_attribute="size",
        data_name="name",
        data_uid=None,
        data_reference="guid",
        data_attributes_list=DEVICE_ATTRIBUTES_POOL,
    ),
    TrueNASSensorEntityDescription(
        key="pool_allocated",
        name="allocated",
        icon=ICON_DATABASE_SETTINGS,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_unit_of_measurement=UnitOfInformation.GIBIBYTES,
        suggested_display_precision=0,
        device_class=SensorDeviceClass.DATA_SIZE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="Pools",
        data_path="pool",
        data_attribute="allocated",
        data_name="name",
        data_uid=None,
        data_reference="guid",
        data_attributes_list=DEVICE_ATTRIBUTES_POOL,
    ),
    TrueNASSensorEntityDescription(
        key="pool_errors",
        name="errors",
        icon="mdi:alert-circle-outline",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="Pools",
        data_path="pool",
        data_attribute="errors",
        data_name="name",
        data_uid=None,
        data_reference="guid",
        data_attributes_list=DEVICE_ATTRIBUTES_POOL_ERRORS,
    ),
    TrueNASSensorEntityDescription(
        key="pool_fragmentation",
        name="fragmentation",
        icon="mdi:chart-pie",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="Pools",
        data_path="pool",
        data_attribute="fragmentation",
        data_name="name",
        data_uid=None,
        data_reference="guid",
        data_attributes_list=DEVICE_ATTRIBUTES_POOL,
    ),
    TrueNASSensorEntityDescription(
        key="cloudsync",
        name="",
        icon="mdi:cloud-upload",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="Cloudsync",
        data_path="cloudsync",
        data_attribute="state",
        data_name="description",
        data_uid=None,
        data_reference="id",
        data_attributes_list=DEVICE_ATTRIBUTES_CLOUDSYNC,
        func="TrueNASCloudsyncSensor",
    ),
    TrueNASSensorEntityDescription(
        key="replication",
        name="",
        icon="mdi:transfer",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="Replication",
        data_path="replication",
        data_attribute="state",
        data_name="name",
        data_uid=None,
        data_reference="id",
        data_attributes_list=DEVICE_ATTRIBUTES_REPLICATION,
        func="TrueNASReplicationSensor",
    ),
    TrueNASSensorEntityDescription(
        key="rsynctask",
        name="",
        icon="mdi:folder-sync",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="Rsync tasks",
        data_path="rsynctask",
        data_attribute="state",
        data_name="desc",
        data_uid=None,
        data_reference="id",
        data_attributes_list=DEVICE_ATTRIBUTES_RSYNC,
        func="TrueNASRsyncSensor",
    ),
    TrueNASSensorEntityDescription(
        key="snapshottask",
        name="",
        icon="mdi:checkbox-marked-circle-plus-outline",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="Snapshot tasks",
        data_path="snapshottask",
        data_attribute="state",
        data_name="dataset",
        data_uid=None,
        data_reference="id",
        data_attributes_list=DEVICE_ATTRIBUTES_SNAPSHOTTASK,
        func="TrueNASSnapshotTaskSensor",
    ),
    TrueNASSensorEntityDescription(
        key="traffic_rx",
        name="RX",
        icon="mdi:download-network-outline",
        native_unit_of_measurement=UnitOfDataRate.KIBIBYTES_PER_SECOND,
        suggested_unit_of_measurement=UnitOfDataRate.MEGABYTES_PER_SECOND,
        suggested_display_precision=2,
        device_class=SensorDeviceClass.DATA_RATE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="Network",
        data_path="interface",
        data_attribute="rx",
        data_name="name",
        data_uid=None,
        data_reference="id",
        data_attributes_list=DEVICE_ATTRIBUTES_NETWORK,
        data_exclude=("link_state", LINK_STATE_DOWN),
    ),
    TrueNASSensorEntityDescription(
        key="traffic_tx",
        name="TX",
        icon="mdi:upload-network-outline",
        native_unit_of_measurement=UnitOfDataRate.KIBIBYTES_PER_SECOND,
        suggested_unit_of_measurement=UnitOfDataRate.MEGABYTES_PER_SECOND,
        suggested_display_precision=2,
        device_class=SensorDeviceClass.DATA_RATE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="Network",
        data_path="interface",
        data_attribute="tx",
        data_name="name",
        data_uid=None,
        data_reference="id",
        data_attributes_list=DEVICE_ATTRIBUTES_NETWORK,
        data_exclude=("link_state", LINK_STATE_DOWN),
    ),
    TrueNASSensorEntityDescription(
        key="ups_charge",
        name="Charge",
        icon="mdi:battery-charging",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="UPS",
        data_path="ups",
        data_attribute="battery_charge",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="ups_runtime",
        name="Runtime",
        icon="mdi:timer-outline",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="UPS",
        data_path="ups",
        data_attribute="runtime_seconds",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="ups_load",
        name="Load",
        icon="mdi:gauge",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="UPS",
        data_path="ups",
        data_attribute="load",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="ups_voltage",
        name="Voltage",
        icon="mdi:sine-wave",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="UPS",
        data_path="ups",
        data_attribute="voltage",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="ups_current",
        name="Current",
        icon="mdi:current-ac",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="UPS",
        data_path="ups",
        data_attribute="current",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="ups_frequency",
        name="Frequency",
        icon="mdi:sine-wave",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="UPS",
        data_path="ups",
        data_attribute="frequency",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="ups_temperature",
        name="Temperature",
        icon="mdi:thermometer",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="UPS",
        data_path="ups",
        data_attribute="temperature",
        data_name=None,
        data_uid=None,
        data_reference=None,
    ),
    TrueNASSensorEntityDescription(
        key="directoryservices",
        name="Status",
        icon="mdi:domain",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="Directory Services",
        data_path="directoryservices",
        data_attribute="status",
        data_name="domain",
        data_uid=None,
        data_reference="id",
        data_attributes_list=DEVICE_ATTRIBUTES_DIRECTORYSERVICE,
    ),
)


class SensorService(NamedTuple):
    """Service definition."""

    name: str
    schema: Any
    action: str


SENSOR_SERVICES: tuple[SensorService, ...] = (
    SensorService(SERVICE_CLOUDSYNC_RUN, SCHEMA_SERVICE_CLOUDSYNC_RUN, "start"),
    SensorService(SERVICE_CLOUDSYNC_ABORT, SCHEMA_SERVICE_CLOUDSYNC_ABORT, "stop"),
    SensorService(SERVICE_RSYNC_RUN, SCHEMA_SERVICE_RSYNC_RUN, "start"),
    SensorService(SERVICE_REPLICATION_RUN, SCHEMA_SERVICE_REPLICATION_RUN, "start"),
    SensorService(SERVICE_SNAPSHOTTASK_RUN, SCHEMA_SERVICE_SNAPSHOTTASK_RUN, "start"),
    SensorService(
        SERVICE_DATASET_SNAPSHOT, SCHEMA_SERVICE_DATASET_SNAPSHOT, "snapshot"
    ),
    SensorService(SERVICE_DATASET_LOCK, SCHEMA_SERVICE_DATASET_LOCK, "lock"),
    SensorService(SERVICE_DATASET_UNLOCK, SCHEMA_SERVICE_DATASET_UNLOCK, "unlock"),
    SensorService(SERVICE_SYSTEM_REBOOT, SCHEMA_SERVICE_SYSTEM_REBOOT, "restart"),
    SensorService(SERVICE_SYSTEM_SHUTDOWN, SCHEMA_SERVICE_SYSTEM_SHUTDOWN, "stop"),
)
