name: Auto Comment Conflicts
on:
  push:
    branches: [main, master]
  pull_request_target:
    types: [synchronize, opened]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check for conflicts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
