name: Release

on:
  release:
    types: [published]

jobs:

  release_zip:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get version number
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/} # Remove refs/tags/
          TAG_NAME=${TAG_NAME#v}            # Remove leading v if present
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Update version number in manifest
        run: |
          python3 ${{ github.workspace }}/.github/update_version.py --version $TAG_NAME

      - name: Zip truenas dir
        run: |
          cd ${{ github.workspace }}/custom_components/truenas
          zip truenas.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@14569a2d348419d066e34e5dfa65071ecd30b64b # v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/truenas/truenas.zip
          asset_name: truenas.zip
          tag: ${{ github.ref }}
          overwrite: true

  releasenotes:
    name: Prepare releasenotes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.13

      - name: Install requirements
        run: |
          python3 -m pip install setuptools wheel PyGithub

      - name: Update release notes
        run: |
          python3 ${{ github.workspace }}/.github/generate_releasenotes.py --token ${{ secrets.GITHUB_TOKEN }} --release yes --tag ${{ github.ref }}
